### ISSUE TITLE
Problem z instalacją pakietów

### ISSUE THREAD

**Issue by gbananachewicz** [zuzia-dev/Easybox-904xDSL#1]
Instalacja pakietów -  brak zlib libc itp. Inne dostępne apki także się kończą błędem.  Błąd aktualizacji z repo 
src/gz easybox904_core http://zuza.webd.pro/testing/repo/eb904/v1-SMP/core
src/gz easybox904_easybox904 http://zuza.webd.pro/testing/repo/eb904/v1-SMP/easybox904

Instalacja zerotier log

Installing zerotier (1.6.2-2) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/zerotier_1.6.2-2_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for zerotier:
 *      libc
 *      libpthread
 *      libstdcpp6
 *      kmod-tun
 *      libc
 * opkg_install_cmd: Cannot install package zerotier.

Mój sprzęt to 904xdsl
System
Nazwa hosta	EasyBOX
Model	Easybox 904xDSL
Architektura	xRX200 rev 1.2
Wersja firmware	OpenWrt SNAPSHOT r14162-ef765ceb09 / LuCI Master git-20.226.17214-f2e9031
Wersja kernela	

Flash ma ok. 50MB wolnego miejsca zamiast 250MB
OPKG UPDATE ma błędy
samba i luci samba błędy

**Comment by gbananachewicz** [comment]
OpenWrt 19.07 SNAPSHOT / Kernel 5.4.77 VPE / xDSL VoIP-GSM Gateway / Asterisk 18.0.1 LTS

jest to samo po instalacji np. samby kończy się na czerwonym ekranie routera z komunikatem o TFTP

**Comment by zuzia-dev** [comment]
Przepraszam, że odpowiadam dopiero teraz.  Zmień bootloader na odblokowany. Jeśli nie pomoże prawdopodobnie masz uszkodzony flash, dlatego próba instalacji kończy się restartem.
