### ISSUE TITLE
Not work after 2 reboots!

### ISSUE THREAD

**Issue by Lexon10** [zuzia-dev/Easybox-904xDSL#3]
Cheers.I used your instructions and flashed the openwrt router. But after 2 reboots, the display shows that the router can not be booted and needs to be restored. Maybe I missed something?

**Comment by Meierhans2** [comment]
Installing hacked bootloader like explained here fixed this for me:
https://openwrt.org/toh/astoria/arcadyan_astoria_easybox_904xdsl_r01#installing_openwrt_the_easy_way
