### ISSUE TITLE
Upgrade recovery & system openwrt

### ISSUE THREAD

**Issue by guntermiller** [zuzia-dev/Easybox-904xDSL#5]
Thank you very much for your work. Are you planning to upgrade to new kernel and new images supporting adsl and voip telephony? Best regards, Gunter.

**Comment by zuzia-dev** [comment]
I have no time to do this, but one version is already available: https://github.com/Firmware-routers/Easybox-904-xDSL/tree/main/Repository/EB904xDSL/VPE/v1
Requires testing.

**Comment by zuzia-dev** [comment]
Update: OpenWrt 21.02.7 with VPE support: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/VPE/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-vpe-squashfs-sysupgrade.bin
