### ISSUE TITLE
2,4GHz network does not work

### ISSUE THREAD

**Issue by mailyspamy** [zuzia-dev/Easybox-904xDSL#6]
Hi,
I tried both images SMP and VPE and it is not possible to connect to 2,4GHz network.
Image flashed as sysupgrade over luci without keeping settings.
Tried default SSID and also changed one.

**Comment by zuzia-dev** [comment]
Hi!
Thank you for reporting. I confirm the error, but unfortunately I don't know the solution to a problem. I will try to fix in the next firmware version.

**Comment by ivamaan** [comment]
> Hi,
> 
> I tried both images SMP and VPE and it is not possible to connect to 2,4GHz network.
> 
> Image flashed as sysupgrade over luci without keeping settings.
> 
> Tried default SSID and also changed one.

Confirmed.

**Comment by zuzia-dev** [comment]
Hi @mailyspamy @ivamaan 
Update: The problem has been resolved in the new version of OpenWrt 21.02.7:
VPE: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/VPE/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-vpe-squashfs-sysupgrade.bin
SMP: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/SMP/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-smp-squashfs-sysupgrade.bin
