### ISSUE TITLE
OPKG update fails / OPKG-Aktualisierung schlägt fehl

### ISSUE THREAD

**Issue by icke68746** [zuzia-dev/Easybox-904xDSL#7]
Hello Zuzia-dev,
first of all many thanks for the good work! I am very glad that you were able to fix the big problems with these routers. I've been following it since about 2018. I'm going to use this router as my main router now.
I have a problem with the OPKG update. When some packages are updated, errors occur so badly that the router has to be reset afterwards. Some packages can be updated or reinstalled without problems (e.g. adblock).
Maybe you can give me some instructions on how to fix this myself?
I use the version
arcadyan,vgv952cjw33-e-ir-vpe
OpenWrt SNAPSHOT Easybox 904 xDSL'
Linux version 5.4.116 (EasyBOX@904xDSL) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 unknown)) #0 SMP Sat May 1 11:18:07 2021

Many greetings from Germany, Icke

Translated with www.DeepL.com/Translator (free version)

`root@EasyBOX: ~$ opkg list-upgradable | cut -f 1 -d ' ' | xargs opkg upgrade
Upgrading terminfo on root from 6.2-2 to 6.4-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/terminfo_6.4-1_mips_24kc.ipk
Upgrading luci-proto-wireguard on root from git-21.117.73295-1d44fec to git-22.339.34491-785792a...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-proto-wireguard_git-22.339.34491-785792a_all.ipk
Installing libucode20220812 (2023-01-09-8dad974b-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/libucode20220812_2023-01-09-8dad974b-1_mips_24kc.ipk
Installing ucode (2023-01-09-8dad974b-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/ucode_2023-01-09-8dad974b-1_mips_24kc.ipk
Removing obsolete file /usr/libexec/rpcd/luci.wireguard.
Upgrading iwinfo on root from 2021-04-30-c45f0b58-1 to 2023-01-21-f7661386-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/iwinfo_2023-01-21-f7661386-1_mips_24kc.ipk
Installing libnl-tiny2022-11-01 (2022-11-01-db3b2cdb-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/libnl-tiny2022-11-01_2022-11-01-db3b2cdb-1_mips_24kc.ipk
Upgrading liblucihttp0 on root from 2019-07-05-a34a17d5-1 to 2022-07-08-6e68a106-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/liblucihttp0_2022-07-08-6e68a106-1_mips_24kc.ipk
Upgrading cgi-io on root from 2020-10-27-ab4c3471-19 to 2022-08-10-901b0f04-21...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/cgi-io_2022-08-10-901b0f04-21_mips_24kc.ipk
Installing libubox20220927 (2022-09-27-ea560134-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/libubox20220927_2022-09-27-ea560134-1_mips_24kc.ipk
Installing libubus20220601 (2022-06-01-2bebf93c-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/libubus20220601_2022-06-01-2bebf93c-1_mips_24kc.ipk
Upgrading luci-lib-base on root from git-21.117.73295-1d44fec to git-22.308.54612-9118452...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-lib-base_git-22.308.54612-9118452_all.ipk
Upgrading luci-proto-gre on root from git-21.117.73295-1d44fec to git-21.158.43143-b4c394f...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-proto-gre_git-21.158.43143-b4c394f_all.ipk
Upgrading ntfs-3g-utils on root from 2017.3.23-4-fuseext to 2022.5.17-1-fuseint...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/ntfs-3g-utils_2022.5.17-1-fuseint_mips_24kc.ipk
Removing obsolete file /sbin/mkfs.ntfs.
Upgrading luci-i18n-wol-pl on root from git-21.117.73295-1d44fec to git-23.016.72713-5455a54...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-i18n-wol-pl_git-23.016.72713-5455a54_all.ipk
Upgrading luci-proto-vxlan on root from git-21.117.73295-1d44fec to git-21.148.48881-79947af...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-proto-vxlan_git-21.148.48881-79947af_all.ipk
Upgrading luci-app-nlbwmon on root from git-21.117.73295-1d44fec to git-23.013.73612-7c7ac8b...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-app-nlbwmon_git-23.013.73612-7c7ac8b_all.ipk
Upgrading mkf2fs on root from 1.14.0-1 to 1.15.0-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/mkf2fs_1.15.0-1_mips_24kc.ipk
Upgrading opkg on root from 2021-03-15-5936c4f9-1 to 2022-02-24-d038e5b6-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/opkg_2022-02-24-d038e5b6-1_mips_24kc.ipk
Upgrading luci-app-opkg on root from git-21.117.73295-1d44fec to git-23.009.82915-ec3aac4...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/luci/luci-app-opkg_git-23.009.82915-ec3aac4_all.ipk
Upgrading ubus on root from 2021-02-15-2537be01-1 to 2022-06-01-2bebf93c-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/ubus_2022-06-01-2bebf93c-1_mips_24kc.ipk
Installing libblobmsg-json20220927 (2022-09-27-ea560134-1) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/libblobmsg-json20220927_2022-09-27-ea560134-1_mips_24kc.ipk
Upgrading iw on root from 5.9-1 to 5.19-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/iw_5.19-1_mips_24kc.ipk
Installing libnl-tiny2022-11-01 (2022-11-01-db3b2cdb-1) to root...
Upgrading libuci20130104 on root from 2021-04-14-4b3db117-4 to 2021-10-22-f84f49f0-6...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/libuci20130104_2021-10-22-f84f49f0-6_mips_24kc.ipk
Upgrading coreutils-echo on root from 8.32-6 to 9.1-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/coreutils-echo_9.1-1_mips_24kc.ipk
Upgrading rpcd on root from 2021-03-11-ccb75178-1 to 2023-01-21-c0df2a7a-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/rpcd_2023-01-21-c0df2a7a-1_mips_24kc.ipk
Error relocating /lib/libubus.so.20220601: __clock_gettime64: symbol not found
Error relocating /lib/libubox.so.20220927: __clock_gettime64: symbol not found
Upgrading busybox on root from 1.33.0-3 to 1.36.0-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/busybox_1.36.0-1_mips_24kc.ipk
Error relocating /lib/libubus.so.20220601: __clock_gettime64: symbol not found
Error relocating /lib/libubox.so.20220927: __clock_gettime64: symbol not found
Error relocating /lib/libubus.so.20220601: __clock_gettime64: symbol not found
Error relocating /lib/libubox.so.20220927: __clock_gettime64: symbol not found
Removing obsolete file /sbin/vconfig.
Removing obsolete file /usr/sbin/fbset.
Removing obsolete file /usr/sbin/i2cget.
Removing obsolete file /sbin/devmem.
Removing obsolete file /usr/bin/ftpget.
Removing obsolete file /usr/bin/unzip.
Removing obsolete file /usr/bin/ftpput.
Removing obsolete file /usr/bin/bzcat.
Removing obsolete file /usr/sbin/i2cdump.
Removing obsolete file /usr/sbin/i2cdetect.
Removing obsolete file /usr/bin/mkpasswd.
Removing obsolete file /usr/sbin/flash_eraseall.
Removing obsolete file /usr/bin/cryptpw.
Removing obsolete file /usr/bin/timeout.
Removing obsolete file /usr/bin/bunzip2.
Removing obsolete file /usr/sbin/i2cset.
Removing obsolete file /usr/bin/dumpleases.
Upgrading f2fs-tools on root from 1.14.0-1 to 1.15.0-1...
Downloading https://downloads.openwrt.org/snapshots/packages/mips_24kc/base/f2fs-tools_1.15.0-1_mips_24kc.ipk
Error relocating /usr/sbin/opkg-key: __gmtime64_r: symbol not found
Error relocating /usr/sbin/opkg-key: __mktime64: symbol not found
Error relocating /usr/sbin/opkg-key: __fstat_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __clock_settime64: symbol not found
Error relocating /usr/sbin/opkg-key: __clock_gettime64: symbol not found
Error relocating /usr/sbin/opkg-key: __utimes_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __futimens_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __utimensat_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __localtime64_r: symbol not found
Error relocating /usr/sbin/opkg-key: __wait3_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __stat_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __time64: symbol not found
Error relocating /usr/sbin/opkg-key: __nanosleep_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __gettimeofday_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __settimeofday_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __localtime64: symbol not found
Error relocating /usr/sbin/opkg-key: __adjtimex_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __lstat_time64: symbol not found
Error relocating /usr/sbin/opkg-key: __ctime64: symbol not found
Error relocating /usr/sbin/opkg-key: __setitimer_time64: symbol not found`
--------------ORIGINAL-------------
Hallo Zuzia-dev,
erstmal vielen Dank für die gute Arbeit! Ich bin sehr froh, dass Sie die großen Probleme mit diesen Router beheben konnten. Ich verfolge die Entwicklung seit ca. 2018. Ich werde den Router jetzt als Hauptrouter verwenden.
Ich habe ein Problem mit dem OPKG-Updates. Wenn einige Pakete aktualisiert werden, treten so schlimme Fehler auf, dass der Router danach neu aufgesetzt werden muss. Manche Pakete können ohne Probleme aktualisiert oder neu installiert werden (z.B. adblock).
Evtl. können Sie mir eine Anleitung geben, wie ich das selber beheben kann?
Ich verwende die Version:
arcadyan,vgv952cjw33-e-ir-vpe
OpenWrt SNAPSHOT Easybox 904 xDSL'
Linux version 5.4.116 (EasyBOX@904xDSL) (gcc version 8.4.0 (OpenWrt GCC 8.4.0 unknown)) #0 SMP Sat May 1 11:18:07 2021

Viele Grüße aus Deutschland, Icke

**Comment by zuzia-dev** [comment]
Hello @icke68746  
The problem has been resolved in the new version of OpenWrt 21.02.7:
VPE: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/VPE/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-vpe-squashfs-sysupgrade.bin
SMP: https://github.com/zuzia-dev/Easybox-904xDSL-repo-source/blob/main/Firmware/SMP/v2/openwrt-lantiq-xrx200-arcadyan_vgv952cjw33-e-ir-smp-squashfs-sysupgrade.bin
